// File: sidebars.js
// Auto-generated by DocuLinkr

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  projectSidebar: [
    {
      type: 'category',
      label: 'FormuLearn Docs Projects',
      link: {
        type: 'generated-index',
        title: 'FormuLearn Docs Projects',
        slug: '/projects',
        description: 'Browse documentation for each project under FormuLearn Docs.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '.',
        },
      ],
      collapsed: false,
    },
  ],
};

module.exports = sidebars;